name: Build GNUnet multi-arch and create .deb

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Git da usare per il build'
        required: true
        default: 'main'

jobs:
  build-ubuntu:
    strategy:
      matrix:
        arch: [amd64, arm64]
        #arch: [amd64]
        version: [25.04, 24.04]
        exclude:
          - arch: arm64
            version: 25.04
    env:
      VERSION: ${{ github.event.release.tag_name }}
      UPLOAD_URL: ${{ github.event.release.upload_url }}
      OUT_DIR: out/ubuntu/${{ matrix.arch }}
      BUILDER_PATH: builders/Dockerfile.ubuntu
      BUILD_NAME: gnunet-${{ github.event.release.tag_name }}-ubuntu-${{ matrix.version }}-${{ matrix.arch }}
      BRANCH: ${{ github.event.inputs.branch || 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GNUnet repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build GNUnet ${{ env.VERSION }} (${{ env.BUILD_NAME }})
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --file ${{ env.BUILDER_PATH }} \
            --output type=local,dest=${{ env.OUT_DIR }} \
            --build-arg OS_VERSION=${{ matrix.version }} \
            --build-arg BRANCH=${{ env.BRANCH }} \
            .
      - name: Upload .deb to release (${{ env.BUILD_NAME }})
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.OUT_DIR }}/gnunet.deb
          asset_name: ${{ env.BUILD_NAME }}.deb
          asset_content_type: application/vnd.debian.binary-package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}