name: Build GNUnet multi-arch and create .deb

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout GNUnet repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build GNUnet for ${{ matrix.arch }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --file builders/Dockerfile.ubuntu \
            --output type=local,dest=out/${{ matrix.arch }} \
            .
      - name: Upload .deb package for ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: gnunet-ubuntu-${{ matrix.arch }}-deb
          path: out/${{ matrix.arch }}/gnunet.deb