name: Build GNUnet multi-arch and create .deb

on:
  # push:
  #   branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
    env:
      VERSION: ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GNUnet repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build GNUnet for ${{ matrix.arch }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            --file builders/Dockerfile.${{ matrix.os }} \
            --output type=local,dest=out/${{ matrix.arch }} \
            .
      - name: Upload .deb package for ${{ matrix.os }}/${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: gnunet-${{ env.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}-deb
          path: out/${{ matrix.arch }}/gnunet.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./out

      - name: Upload .deb files to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}